services:
  discord-bot:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prepro68-bot
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: ["bun", "run", "start"]
